# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x0c\x63onversation\"H\n\x13\x45nsureThreadRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\"W\n\x0eThreadResponse\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"Z\n\x14\x41ppendMessageRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\"k\n\x0fMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"5\n\x11GetHistoryRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"/\n\x0eHistoryMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"D\n\x12GetHistoryResponse\x12.\n\x08messages\x18\x01 \x03(\x0b\x32\x1c.conversation.HistoryMessage2\x8b\x02\n\x13\x43onversationService\x12O\n\x0c\x45nsureThread\x12!.conversation.EnsureThreadRequest\x1a\x1c.conversation.ThreadResponse\x12R\n\rAppendMessage\x12\".conversation.AppendMessageRequest\x1a\x1d.conversation.MessageResponse\x12O\n\nGetHistory\x12\x1f.conversation.GetHistoryRequest\x1a .conversation.GetHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENSURETHREADREQUEST']._serialized_start=36
  _globals['_ENSURETHREADREQUEST']._serialized_end=108
  _globals['_THREADRESPONSE']._serialized_start=110
  _globals['_THREADRESPONSE']._serialized_end=197
  _globals['_APPENDMESSAGEREQUEST']._serialized_start=199
  _globals['_APPENDMESSAGEREQUEST']._serialized_end=289
  _globals['_MESSAGERESPONSE']._serialized_start=291
  _globals['_MESSAGERESPONSE']._serialized_end=398
  _globals['_GETHISTORYREQUEST']._serialized_start=400
  _globals['_GETHISTORYREQUEST']._serialized_end=453
  _globals['_HISTORYMESSAGE']._serialized_start=455
  _globals['_HISTORYMESSAGE']._serialized_end=502
  _globals['_GETHISTORYRESPONSE']._serialized_start=504
  _globals['_GETHISTORYRESPONSE']._serialized_end=572
  _globals['_CONVERSATIONSERVICE']._serialized_start=575
  _globals['_CONVERSATIONSERVICE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
