# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cintent.proto\x12\x06intent\",\n\x0bHistoryItem\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"F\n\x0f\x43lassifyRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12$\n\x07history\x18\x02 \x03(\x0b\x32\x13.intent.HistoryItem\"p\n\x10\x43lassifyResponse\x12\x18\n\x10\x63onfidence_score\x18\x01 \x01(\x02\x12\x10\n\x08is_clear\x18\x02 \x01(\x08\x12\x1e\n\x16\x63larification_question\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t2N\n\rIntentService\x12=\n\x08\x43lassify\x12\x17.intent.ClassifyRequest\x1a\x18.intent.ClassifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYITEM']._serialized_start=24
  _globals['_HISTORYITEM']._serialized_end=68
  _globals['_CLASSIFYREQUEST']._serialized_start=70
  _globals['_CLASSIFYREQUEST']._serialized_end=140
  _globals['_CLASSIFYRESPONSE']._serialized_start=142
  _globals['_CLASSIFYRESPONSE']._serialized_end=254
  _globals['_INTENTSERVICE']._serialized_start=256
  _globals['_INTENTSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
