# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x06memory\"D\n\x13MemorySearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"(\n\x14MemorySearchResponse\x12\x10\n\x08\x63ontexts\x18\x01 \x03(\t\"X\n\x12MemoryStoreRequest\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"!\n\x13MemoryStoreResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x96\x01\n\rMemoryService\x12\x43\n\x06Search\x12\x1b.memory.MemorySearchRequest\x1a\x1c.memory.MemorySearchResponse\x12@\n\x05Store\x12\x1a.memory.MemoryStoreRequest\x1a\x1b.memory.MemoryStoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMORYSEARCHREQUEST']._serialized_start=24
  _globals['_MEMORYSEARCHREQUEST']._serialized_end=92
  _globals['_MEMORYSEARCHRESPONSE']._serialized_start=94
  _globals['_MEMORYSEARCHRESPONSE']._serialized_end=134
  _globals['_MEMORYSTOREREQUEST']._serialized_start=136
  _globals['_MEMORYSTOREREQUEST']._serialized_end=224
  _globals['_MEMORYSTORERESPONSE']._serialized_start=226
  _globals['_MEMORYSTORERESPONSE']._serialized_end=259
  _globals['_MEMORYSERVICE']._serialized_start=262
  _globals['_MEMORYSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
