# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"d\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05sites\x18\x02 \x03(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x12\n\nuse_tavily\x18\x04 \x01(\x08\x12\x12\n\nuse_google\x18\x05 \x01(\x08\"<\n\x0cSearchResult\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"7\n\x0eSearchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.search.SearchResult2H\n\rSearchService\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=124
  _globals['_SEARCHRESULT']._serialized_start=126
  _globals['_SEARCHRESULT']._serialized_end=186
  _globals['_SEARCHRESPONSE']._serialized_start=188
  _globals['_SEARCHRESPONSE']._serialized_end=243
  _globals['_SEARCHSERVICE']._serialized_start=245
  _globals['_SEARCHSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
