# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: synthesis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'synthesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsynthesis.proto\x12\tsynthesis\"<\n\x0cResearchItem\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\",\n\x0bHistoryItem\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x88\x01\n\x10SynthesisRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12.\n\rresearch_data\x18\x02 \x03(\x0b\x32\x17.synthesis.ResearchItem\x12\'\n\x07history\x18\x03 \x03(\x0b\x32\x16.synthesis.HistoryItem\x12\x0c\n\x04gaps\x18\x04 \x03(\t\"K\n\x11SynthesisResponse\x12\x0e\n\x06report\x18\x01 \x01(\t\x12\x11\n\tcitations\x18\x02 \x03(\t\x12\x13\n\x0btoken_usage\x18\x03 \x01(\x05\"f\n\x12GapAnalysisRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12.\n\rresearch_data\x18\x02 \x03(\x0b\x32\x17.synthesis.ResearchItem\x12\x11\n\titeration\x18\x03 \x01(\x05\"=\n\x13GapAnalysisResponse\x12\x18\n\x10\x63onfidence_score\x18\x01 \x01(\x02\x12\x0c\n\x04gaps\x18\x02 \x03(\t\"\x1b\n\nTokenChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2\xf3\x01\n\x10SynthesisService\x12G\n\nSynthesize\x12\x1b.synthesis.SynthesisRequest\x1a\x1c.synthesis.SynthesisResponse\x12L\n\x0b\x41nalyzeGaps\x12\x1d.synthesis.GapAnalysisRequest\x1a\x1e.synthesis.GapAnalysisResponse\x12H\n\x10SynthesizeStream\x12\x1b.synthesis.SynthesisRequest\x1a\x15.synthesis.TokenChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'synthesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESEARCHITEM']._serialized_start=30
  _globals['_RESEARCHITEM']._serialized_end=90
  _globals['_HISTORYITEM']._serialized_start=92
  _globals['_HISTORYITEM']._serialized_end=136
  _globals['_SYNTHESISREQUEST']._serialized_start=139
  _globals['_SYNTHESISREQUEST']._serialized_end=275
  _globals['_SYNTHESISRESPONSE']._serialized_start=277
  _globals['_SYNTHESISRESPONSE']._serialized_end=352
  _globals['_GAPANALYSISREQUEST']._serialized_start=354
  _globals['_GAPANALYSISREQUEST']._serialized_end=456
  _globals['_GAPANALYSISRESPONSE']._serialized_start=458
  _globals['_GAPANALYSISRESPONSE']._serialized_end=519
  _globals['_TOKENCHUNK']._serialized_start=521
  _globals['_TOKENCHUNK']._serialized_end=548
  _globals['_SYNTHESISSERVICE']._serialized_start=551
  _globals['_SYNTHESISSERVICE']._serialized_end=794
# @@protoc_insertion_point(module_scope)
